- addAnimal.php
Added a comment to the addAnimal.php file on line 7 for the Github assignment
> Added a comment to addAnimal.php

- angelGiftForm.php
Added back button to the bottom of the form
> Added back button to angel gift form

- fillForm.php
> Added return to dashboard button to the forms page

- holidayMealBagForm.php
Added margins, and kept the cancel button.
> Sj 31 holiday meal bag form

- fillForm.php
Removed duplicate code which added a second program interest form button to the page.
> Removed one of the extra program interest form buttons

- sql/4dbHolidayMealBag.sql
Added the table for the Holiday Meal Bag
> Holiday Meal Bag Table

- database/dbChildren.php
- domain/Children.php
Created the dbChildren and Childen.php files with some functions.
The retrieve_children_by_email() function is used to retrieve all children in a family from the database using the family email.
> Added Children.php and dbChilren.php files

- sql/8dbHolidayPartyForm.sql
-Added table for the holiday party form
> added table for holiday party form

- database/dbAngelGiftForm.php
- database/dbChildren.php
Fixed minor issue in creating an account
> Angel gift debug

- holidayMealBagForm.php
Fixed the issues with the phone number and deleted the redundant validation of the photo release
> SJ-77-BackendFunctionalityHMBF

- database/dbProgramInterestForm.php
- programInterestForm.php
- sql/10programInterestForm.sql
Program Interest Form Backend
Added SQL tables for program interest form which has junction tables connecting dbProgramInterests and dbTopicInterests to dbProgramInterestForm. Availability also has its own table in dbAvailability. 
Because there are so many tables to insert data into, I thought it would be a good idea to put all queries within a mysqli transaction which will commit all of them if there are no problems or errors. However, if there are any, it will roll them back and no queries will be executed. I did this so if one insert query has no issues but another one does, it will not just execute the one that worked. Tested it and filling out the form should not produce any errors, but I added this just in case.
I also included autopopulate for most fields. They are only …
> SJ-90 Program Interest Form Backend

- familyAccountDashboard.php
- images/add-square-svgrepo-com.svg
Pull request for assignment. Just adds the add child dashboard button to the family account dashboard page
> Add dashboard item for adding children

- css/base.css
- database/dbFamily.php
- familyView.php
- findFamily.php
As a staff member I would like to archive data so that I can remove but save family information
1. Family can be archived from staff account
3. Family can be unarchived from staff account
4. Archived families can be view from the staff account
> Added archive family data functionality and updated search

- database/dbFamily.php
Deleted some comments that broke main
> Removed some comments

- database/dbChildren.php
- database/dbProgramInterestForm.php
- database/dbSchoolSuppliesForm.php
- programInterestForm.php
- schoolSuppliesForm.php
- sql/10programInterestForm.sql
- sql/5schoolSuppliesForm.sql
I started to work on the back-end stuff but will need some help finishing up as I have some errors. I am too tired to think of it right now. 😪
> Sj 41 school supplies backend

- addChild.php
- familyAccountDashboard.php
- header.php
- index.php
- login.php
Changed login so that the login dropdown will display 'admin' instead of 'staff'. Use vmsroot to login to the admin page. Everywhere in the code that checks if the user is staff now checks if the user is an admin instead
> Sj 102 [Add admin login]

- childAccount.php
- childrenInAccount.php
- css/base.css
- familyAccountDashboard.php
- familyView.php
- findFamily.php
childAccount.php
---
- changed format to fieldsets for cleaner look
childrenInAccount.php
---
- slight adjustments to table format for easier viewing of all accounts
css/base.css
---
- #view-family class created for fieldset and legend
familyAccountDashboard.php
---
- added space between hello and name
familyView.php
---
- changed format of displayed information
- for staff: added summary of child accounts in that family account, added links to view child accounts
- styled buttons
findFamily,php
---
- changed table column names to match
- removed emergency contact information from search display (it was too large)
> SJ-93: View Accounts Update

- sql/10dbChildCareWaiverForm.sql
Added table for the child care waiver form.
> SJ-83-dbChildCareForm

- sql/12dbSpringBreakCampForm.sql
Added table for spring break camp form.
> SJ-85-dbSpringBreakForm

- createStaffAccount.php
- database/dbStaff.php
- domain/Staff.php
- header.php
- index.php
- login.php
- sql/13dbStaff.sql
This pull request has code that creates a dbStaff data table and the backend functionality to insert staff data. Staff account creation happens at the admin level, but once an account is made the staff member can then login to their account. Index.php is used as both the staff and admin dashboard, but if the account is an admin account, the dashboard will have the 'add staff account' option. I removed a lot of the dashboard items from the original codebase so that the dashboard is cleaned up, but have them saved elsewhere in case we'll need them in the future.
> Sj 98 [Create Staff login]

- addChild.php
- angelGiftForm.php
- database/dbChildren.php
- database/dbFamily.php
- domain/Children.php
- domain/Family.php
- familyAccount.php
- programInterestForm.php
- sql/11alterFamily.sql
- sql/1dbFamily.sql
- sql/2dbChildren.sql
Added extra columns in dbFamily
- neighborhood
- income
- isHispanic
- race
Added extra colums to dbChildren
- address
- neighborhood
- city
- state
- zip
- school
- grade
- race
- isHispanic
Added two tables, dbLangages and dbAssistance which connect to dbFamily.
Had to update the family signup in familyAccount.php for adding data to these new tables and columns.
Also had to update the Children.php and Family.php class files to include new fields and functions for these new additions.
Changed a few lines of code in other files to get things working and fix some errors.
Also added some insert statements in the sql files to add families and children for testing.
> SJ-100 Add Extra Columns to dbFamily and dbChildren

- sql/12dbSpringBreakCampForm.sql
dbSpringBreakCampForm: 
Changed constraint to FK_dbspringbreakcampform_child_id.
> update sql syntax

- familyAccountDashboard.php
- familyView.php
- fillForm.php
- holidayMealBagForm.php
- index.php
This pull request has code that allows a staff member to log into their account, search a family account, click on 'fill form' and fill in the Holiday Meal Bag form on behalf of the family account.
> Sj 106 [As a staff member I would like to fill out the Holiday Meal Bag Form for a family account]

- childAccount.php
- database/dbAngelGiftForm.php
- database/dbChildren.php
- database/dbFamily.php
- findChildren.php
- header.php
- index.php
Added extra criteria to family search
Created children search
> SJ-99 Expand Family Search With Extra Criteria

- actualActivityForm.php
- css/base.css
- database/dbActualActivityForm.php
- familyAccountDashboard.php
- fillForm.php
- sql/7actualActivityForm.sql
Full Actual Activity Form Functionality
===
actualActivityForm.php
---
- takes dynamic inputs for attendance
- validates inputs before inserting to database
- provides warnings to user if something is incomplete or invalid without deleting input
dbActualActivityForm:
---
- reformatted to add data correctly
- handles exceptions
Other Fixes
---
- fillForm.php: actual activity form only available to staff members
- family dashboard: fixed 'hello (name)' message to have a space :)
> SJ-88: Actual Activity Form new

- login.php
- sql/15createDummyStaff.sql
Test staff account credentials:
Email: teststaff@gmail.com
Password: vmsroot
> Add test staff account and remove debug code

- changePassword.php
- database/dbStaff.php
- database/dbVolunteers.php
- login.php
You can test with the following credentials:
User: volunteer@mail.com
Pass: vmsroot
> [Sj-105] Add volunteer login & bug fixes

- database/dbFieldTripWaiverForm.php
- fieldTripWaiver.php
- sql/11dbFieldTrpWaiverForm.sql
As a family, I would like to fill out a waiver form so that I can leave my kid(s) to the program.
> SJ-89 field trip waiver backend

- database/dbChildren.php
- database/dbHolidayPartyForm.php
- familyAccountDashboard.php
- holidayPartyForm.php
- sql/16updatedbHolidayPartyForm.sql
This pull request has code that allows the family to fill out the BrainBuilders holiday party form. Children for the account are listed in the dropdown of the form and the user can select which child they want to sign up. The only thing is that a child can only enroll in the BrainBuilder Holiday party if they are part of the BrainBuilder program. Currently I don't think we have that implemented yet to check so I can add that check later.
> Sj 131 [As a family, I would like to enroll my child in the BrainBuilders Holiday Party]

- database/dbProgramInterestForm.php
- fillForm.php
- programInterestForm.php
Added functionality for staff to fill the program interest form for a family.
Added functionality for staff and families to view the form and its data after submitting. Fields in the form are filled using data from dbProgramInterestForm and the tables associated with it. Fields are also disabled. Made some php functions that I used inside the HTML input attributes to do this.
Also added a few smaller things like autopopulate for the neighborhood field.
Attached below is a screenshot of a completed program interest form.
> SJ-113 Staff Fill Program Interest Form

- angelGiftForm.php
- fillForm.php
- sql/16updateAngelGiftPhone.sql
- sql/3angelGiftForm.sql
Added functionality for staff to fill the angel wish gift form for a family
> SJ-109 Staff Fill Angel Wish Gift Form

- sql/16updateActualActivityForm
- sql/16updateActualActivityForm.sql
Changes
===
1. Drops old dbActualActivityForm if it exists
2. Drops old Attendees table if it exists
3. Creates new tables
> SJ-139: New .sql for ActualActivityForm

- angelGiftForm.php
- programInterestForm.php
Found a few errors where if a staff backs out from the angel gift form page, it gives an error and the page breaks when re entering the form. This code here should fix it. Also re added the form fail display message to the program interest form since I accidentally removed it.
> Staff Form Error Fixes

- childCareWaiverForm.php
- database/dbChildCareForm.php
- sql/10dbChildCareWaiverForm.sql
**Prerequisites**:  
- Ensure the following tables exist in your `localhost` database on PhpMyAdmin:  
- `dbChildren`  
- `dbUnallowedFoods`  
- `dbChildCareWaiver` (updated sql table structure per this PR).  
- Import the necessary SQL files or verify the table structures match those listed above. 
**Testing the Form**:  
1. Sign in as a family member.
2. Ensure at lease one child already exist within the family account, if not add one with the 'add child' function.
3. Navigate to the child care waiver form.
4. Use the dropdown menu to select a child at the top of the form.  
5. Complete the form fields with sample data.  
6. Submit the form and confirm:  
- Data is correctly inserted into the `dbUnallowedFoods`, `dbChildCareWaiver`, and `dbChildren` tables.  
- The child is no longer in …
> SJ-137-childCareWaiverBackend

- childCareWaiverForm.php
- fillForm.php
Staff can now fill out the child care waiver form.
1. git checkout SJ-111-childCareWaiverFormStaff
3. Sign in as a staff member.
4. Navigate to the Child Care Waiver Form.
5. Select a child from the drop-down menu.
6. Fill out the rest of the form.
7. Submit the form.
> SJ-111-childCareWaiverFormStaf

- header.php
Code that removes the old navigation bar. Staff and admin now have their own navigation bar. As we finish adding more features, this navigation bar can be updated
> [SJ-142] Updated navbar for staff and admin accounts

- findFamily.php
Re added functionality to search for archived families in family search
> Re added Archived Family Search

- database/dbMessages.php
Removed a few lines from dbMessages.php to fix a few errors
> dbMessages.php Bug Fix

- brainBuildersRegistrationForm.php
- database/dbBrainBuildersRegistration.php
- fillForm.php
- sql/20updateBrainBuildersRegistration.sql
- sql/6brainBuildersRegistrationForm.sql
Pull request that has code to allow a staff or family member to register a child for the Brain Builders Program. A couple of columns aren't normalized, but that can be updated during the maintenance phase.
> Code for a family or staff to enroll child in brain builders registration program

- childAccount.php
- childrenInAccount.php
- header.php
Hopefully last pull request, just made some slight usability improvements
> Quickfixes

- addAttendee.php
- addRouteVolunteer.php
- busMonitorAttendanceForm.php
- database/dbBusMonitorForm.php
- editBusMonitorData.php
- removeAttendee.php
- removeVolunteer.php
- sql/20dbBusMonitorForm.sql
Brief Description:
- A staff member can assign or de-assign a child from dbChildren to a specific route on the bus monitor form.
- A staff member can assign or de-assign a volunteer from dbVolunteers to a specific route on the bus monitor form.
- A staff member can submit the bus monitor form for both the north/south routes by checking off boxes of both volunteers and attendees for specific route locations, if a box is not checked off and the form is submitted they will be marked as absent.
Instructions:
[1]... git fetch
[2]... git checkout SJ-146-busMonitorFormStaff
[3]...Prior to testing on your local host ensure that the dbVolunteers table exist, and there is at least one volunteer present in that table.
[4].. Import my updated sql file from this PR, this will create the tables …
> SJ-146-busMonitorFormStaff

- database/dbAngelGiftForm.php
- database/dbProgramInterestForm.php
- schoolSuppliesForm.php
messed up when merging just needed to add a php tag
> Update for Fixes
